---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Elastic Redis Cache'
Parameters:
  ClusterNodeType:
    Description: The compute and memory capacity of the nodes in the Redis Cluster
    Type: String
    Default: cache.t2.small
    AllowedValues:
    - cache.m1.small
    - cache.m1.large
    - cache.m1.xlarge
    - cache.m2.xlarge
    - cache.m2.2xlarge
    - cache.m2.4xlarge
    - cache.c1.xlarge
    - cache.t2.micro
    - cache.t2.small
    - cache.t2.medium
    - cache.m3.medium
    - cache.m3.large
    - cache.m3.xlarge
    - cache.m3.2xlarge
    - cache.r3.large
    - cache.r3.xlarge
    - cache.r3.2xlarge
    - cache.r3.4xlarge
    - cache.r3.8xlarge
    ConstraintDescription: must select a valid Cache Node type.
  NetworkStack:
    Description: VPC Stack Name
    Type: String
  EnvironmentName:
    Type: String
Resources:

  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStack}-VPC"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '11211'
          ToPort: '11211'
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStack}-LBSecurityGroupID"

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Cache Subnet Group
      SubnetIds:
        - Fn::ImportValue: 
            Fn::Sub: "${NetworkStack}-PrivateSubnet0SubnetID"
        - Fn::ImportValue: 
            Fn::Sub: "${NetworkStack}-PrivateSubnet1SubnetID"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStack}-PublicSubnet1SubnetID"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStack}-PublicSubnet2SubnetID"

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType:
        Ref: ClusterNodeType
      Engine: redis
      NumCacheNodes: '1'
      CacheSubnetGroupName: !Ref SubnetGroup
      ClusterName: !Sub "${EnvironmentName}-Redis-Cluster"
      VpcSecurityGroupIds:
        - !GetAtt
          - ElasticacheSecurityGroup
          - GroupId
